# Generated by Django 4.1.4 on 2023-02-23 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0017_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_new_vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Job_type', models.CharField(max_length=30)),
                ('Location', models.TextField()),
                ('No_of_vacancy', models.CharField(max_length=20)),
                ('Min_salary', models.BigIntegerField()),
                ('Experience', models.CharField(max_length=30)),
                ('Date', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile_company')),
            ],
            options={
                'db_table': 'add_new_vacancy',
            },
        ),
    ]
