# Generated by Django 4.1.4 on 2023-02-23 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_new_vacancy',
            name='company',
        ),
    ]
