# Generated by Django 4.1.4 on 2023-03-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_add_new_vacancy_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_new_vacancy',
            name='Min_salary',
            field=models.TextField(),
        ),
    ]
