# Generated by Django 4.1.4 on 2023-02-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_technology',
            new_name='Technology',
        ),
    ]
