# Generated by Django 4.1.4 on 2023-02-04 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_rename_add_technology_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtech_name', models.CharField(max_length=80)),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.technology')),
            ],
            options={
                'db_table': 'subtech_table',
            },
        ),
    ]
