# Generated by Django 4.1.4 on 2023-02-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_subtechnology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('company', models.BigIntegerField()),
            ],
            options={
                'db_table': 'inquiry_table',
            },
        ),
    ]
