# Generated by Django 4.1.4 on 2023-03-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtechnology',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
