# Generated by Django 4.1.4 on 2023-03-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_subtechnology_date_technology_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
