# Generated by Django 4.1.5 on 2023-02-20 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myadmin', '0004_inquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('abstract', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('database', models.CharField(max_length=100)),
                ('tool', models.CharField(max_length=80)),
                ('document', models.CharField(max_length=150)),
                ('sourcecode', models.CharField(max_length=100)),
                ('subtech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.subtechnology')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.technology')),
            ],
            options={
                'db_table': 'upload_project',
            },
        ),
        migrations.CreateModel(
            name='Profile_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BigIntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Profile_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BigIntegerField()),
                ('address', models.TextField()),
                ('about_company', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Post_query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('file', models.CharField(max_length=150)),
                ('subtech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.subtechnology')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.technology')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_query',
            },
        ),
    ]
