# Generated by Django 4.1.4 on 2023-02-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_post_query_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('phone_no', models.BigIntegerField()),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
