# Generated by Django 4.1.4 on 2023-02-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_project',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
