# Generated by Django 4.1.4 on 2023-02-22 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_post_query_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload_project',
        ),
    ]
