# Generated by Django 4.1.4 on 2023-02-22 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_upload_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_query',
            name='user',
        ),
        migrations.RemoveField(
            model_name='upload_project',
            name='user',
        ),
    ]
