# Generated by Django 4.1.4 on 2023-02-22 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_inquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0010_remove_post_query_user_remove_upload_project_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_project1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('abstract', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('database', models.CharField(max_length=100)),
                ('tool', models.CharField(max_length=80)),
                ('document', models.CharField(max_length=150)),
                ('sourcecode', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('subtech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.subtechnology')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.technology')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upload_project',
            },
        ),
        migrations.DeleteModel(
            name='Upload_project',
        ),
    ]
