# Generated by Django 4.1.4 on 2023-02-22 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_upload_project_post_query_user_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='upload_project',
            table='upload_project1',
        ),
    ]
