# Generated by Django 4.1.4 on 2023-02-22 08:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_inquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0013_alter_upload_project_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upload_project',
            new_name='Upload_project1',
        ),
    ]
