# Generated by Django 4.1.4 on 2023-02-24 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_add_new_vacancy_user'),
        ('user', '0018_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='vacancy',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.add_new_vacancy'),
        ),
    ]
