# Generated by Django 4.1.4 on 2023-02-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_resume_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_user',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
