# Generated by Django 4.1.4 on 2023-03-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_profile_user_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_company',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
