# Generated by Django 4.1.4 on 2023-03-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_profile_company_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
