# Generated by Django 4.1.4 on 2023-03-02 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_add_new_vacancy_min_salary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0022_delete_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.add_new_vacancy')),
            ],
            options={
                'db_table': 'resume',
            },
        ),
    ]
